# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback Submission', 'verbose_name_plural': 'Feedback Submissions'},
        ),
        migrations.AlterModelOptions(
            name='kitform',
            options={'verbose_name': 'Missing / Broken Kit', 'verbose_name_plural': 'Missing Kit Reports'},
        ),
    ]
