# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 19:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160819_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 19, 19, 16, 18, 584050, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitform',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 19, 19, 16, 24, 737757, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
