# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kent_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('S', 'Sailing'), ('W', 'Windsurfing')], default='S', max_length=1)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasters.Date')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasters.Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasters.User')),
            ],
        ),
    ]
