# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasters', '0002_auto_20160819_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='time',
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
