# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasters', '0005_date_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='times',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
