# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasters', '0007_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='sailing_spots',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='date',
            name='windsurfing_spots',
            field=models.IntegerField(default=6),
        ),
    ]
