# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kent_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Date')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.User')),
            ],
        ),
    ]
