# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_user_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='date',
        ),
    ]
