# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='activity',
            field=models.CharField(choices=[('S', 'Sailing'), ('W', 'Windsurfing')], default='S', max_length=1),
        ),
    ]
