# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-21 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 8, 21, 23, 31, 38, 261545, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.FilePathField(default='/static/announcement.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
