# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20160821_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
