# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20160823_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
