# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20160824_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
