# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_auto_20160824_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 24, 0, 21, 1, 561082, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
