# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Announcement Title', max_length=40),
        ),
    ]
