# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
