# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20160824_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
