# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
