# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20160930_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
