# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_event_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.FileField(null=True, upload_to='static/img'),
        ),
    ]
