# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-21 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
